import React, { useEffect, useState } from 'react';
import { Alert, Linking, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { api } from '../api';
import { C, s, Btn, In, Stars } from '../ui';

const DAYS = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];
const say = (message) => Platform.OS === 'web' ? window.alert(message) : Alert.alert('PickMe', message);
const hav = (a, b) => { const r = (x) => x * Math.PI / 180; const k = Math.sin(r(b.lat - a.lat) / 2) ** 2 + Math.cos(r(a.lat)) * Math.cos(r(b.lat)) * Math.sin(r(b.lng - a.lng) / 2) ** 2; return 12742 * Math.asin(Math.sqrt(k)); };
const wa = (phone, text) => Linking.openURL(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`);

export const Guest = ({ go }) => <View style={s.card}><Text style={s.name}>Log in to continue</Text><Btn t="Log in / Sign up" onPress={() => go('auth')} /></View>;

export function DetailScreen({ commute, back, need }) {
  const [profile, setProfile] = useState(null); const [sent, setSent] = useState(false);
  useEffect(() => { api(`/api/users/${commute.user._id}`).then(setProfile).catch(() => {}); }, [commute.user._id]);
  const join = () => { if (!need()) return; api('/api/requests', { commuteId: commute._id }).then(() => { setSent(true); say('Request sent! You can also WhatsApp them.'); }).catch((error) => say(error.message)); };
  const message = `Hi ${commute.user.name}! I found you on PickMe. Are you still going ${commute.origin.name} → ${commute.dest.name} around ${commute.startTime}?`;
  const report = () => need() && api('/api/report', { userId: commute.user._id, reason: 'Reported from ride details' }).then(() => say('Reported. Thanks!')).catch((error) => say(error.message));
  const block = () => need() && api('/api/block', { userId: commute.user._id }).then(() => { say('Blocked.'); back(); }).catch((error) => say(error.message));
  return <SafeAreaView style={s.fill}><ScrollView contentContainerStyle={s.pad}><Text onPress={back} style={{ fontSize: 22 }}>←</Text><Text style={s.h2}>Ride Details</Text><View style={s.card}><Text style={s.name}>{commute.user.name}{commute.user.verified ? ' ✔ Verified' : ''}</Text><Text style={s.mute}>★ {commute.user.avg || 'New'} · {commute.user.count} ratings</Text><Text style={{ fontSize: 26, fontWeight: '800', marginVertical: 8 }}>{commute.startTime} – {commute.endTime}</Text><Text>🟢 {commute.origin.name}</Text><Text>🔴 {commute.dest.name}</Text><Text style={{ marginTop: 8 }}>📅 {commute.startDate || '-'} → {commute.endDate || '-'} · {commute.days.map((day) => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day]).join(', ')}</Text><Text style={{ marginTop: 6 }}>💺 {commute.seats} seats · 💰 Rs. {commute.price}/seat · {commute.score}% match</Text></View><Btn yellow t={sent ? 'Request sent ✓' : 'Request to Join  →'} onPress={join} /><Btn dark t="Chat on WhatsApp  →" onPress={() => wa(commute.user.phone, message)} /><Text style={s.lbl}>Reviews</Text>{profile && profile.reviews.length === 0 && <Text style={s.mute}>No reviews yet.</Text>}{profile && profile.reviews.map((review, index) => <View key={index} style={s.card}><Stars v={review.stars} /><Text>{review.comment || '—'}</Text><Text style={s.mute}>by {review.from || 'rider'}</Text></View>)}<View style={{ flexDirection: 'row', gap: 10, marginTop: 10 }}><Btn style={{ flex: 1, backgroundColor: C.lav }} t="Report" onPress={report} /><Btn style={{ flex: 1, backgroundColor: C.red }} t="Block" onPress={block} /></View></ScrollView></SafeAreaView>;
}

export function RequestsScreen() {
  const [data, setData] = useState({ incoming: [], outgoing: [] }); const [tripForm, setTripForm] = useState(null); const [matches, setMatches] = useState([]);
  const load = () => api('/api/requests').then(setData).catch((error) => say(error.message));
  useEffect(() => { load(); api('/api/commutes/mine').then((commutes) => commutes[0] && api('/api/match', commutes[0])).then((result) => result && setMatches(result.slice(0, 3))).catch(() => {}); }, []);
  const act = (id, status) => api(`/api/requests/${id}`, { status }, 'PATCH').then(load);
  const accepted = {}; data.incoming.filter((request) => request.status === 'accepted' && request.commuteId).forEach((request) => { (accepted[request.commuteId._id] = accepted[request.commuteId._id] || { commute: request.commuteId, count: 0 }).count += 1; });
  const finish = () => api('/api/trips', { commuteId: tripForm.commute._id, distanceKm: tripForm.km, fare: tripForm.fare }).then((trip) => { setTripForm(null); say(`Trip recorded! Each person pays Rs. ${trip.perPerson}.`); load(); }).catch((error) => say(error.message));
  return <><Text style={s.h2}>Requests & matches</Text>{matches.length > 0 && <><Text style={s.sectionTitle}>Best matches for your commute</Text>{matches.map((match) => <View key={match._id} style={s.matchCard}><View style={{ flex: 1 }}><Text style={s.name}>{match.user.name}</Text><Text style={s.mute}>★ {match.user.avg || 'New'} · {match.startTime} · {match.origin.name} → {match.dest.name}</Text><Text style={s.matchReason}>Going your way · {match.explanation?.daysOverlap}</Text></View><Text style={s.matchScore}>{match.score}%</Text></View>)}</>}<Text style={s.lbl}>People who want to join you</Text>{data.incoming.length === 0 && <Text style={s.mute}>None yet.</Text>}{data.incoming.map((request) => <View key={request._id} style={s.card}><Text style={s.name}>{request.fromUser?.name}</Text><Text style={s.mute}>{request.commuteId?.origin?.name} → {request.commuteId?.dest?.name} · {request.status}</Text>{request.status === 'pending' && <View style={{ flexDirection: 'row', gap: 10 }}><Btn style={{ flex: 1 }} yellow t="Accept" onPress={() => act(request._id, 'accepted')} /><Btn style={{ flex: 1, backgroundColor: C.red }} t="Reject" onPress={() => act(request._id, 'rejected')} /></View>}{request.status === 'accepted' && <Btn dark t="WhatsApp rider" onPress={() => wa(request.fromUser.phone, 'Hi! Your PickMe request is accepted.')} />}</View>)}{Object.values(accepted).map(({ commute, count }) => <View key={commute._id} style={[s.card, { backgroundColor: C.mint }]}><Text style={s.name}>Ride complete with {count} rider(s)?</Text>{tripForm && tripForm.commute._id === commute._id ? <><Text style={s.lbl}>Distance (km)</Text><In keyboardType="numeric" value={String(tripForm.km)} onChangeText={(value) => setTripForm({ ...tripForm, km: value })} /><Text style={s.lbl}>Total fare (Rs)</Text><In keyboardType="numeric" value={tripForm.fare} onChangeText={(value) => setTripForm({ ...tripForm, fare: value })} placeholder="e.g. 1200" /><Text style={s.mute}>{tripForm.fare ? `Split ${count + 1} ways: Rs. ${Math.round(+tripForm.fare / (count + 1))} each` : 'Enter fare to see split'}</Text><Btn t="Save trip & split cost" onPress={finish} /></> : <Btn yellow t="Complete trip & split cost" onPress={() => setTripForm({ commute, km: Math.round(hav(commute.origin, commute.dest) * 1.3), fare: '' })} />}</View>)}<Text style={s.lbl}>Requests you sent</Text>{data.outgoing.length === 0 && <Text style={s.mute}>None yet.</Text>}{data.outgoing.map((request) => <View key={request._id} style={s.card}><Text style={s.name}>{request.toUser?.name}</Text><Text style={s.mute}>{request.commuteId?.origin?.name} → {request.commuteId?.dest?.name}</Text><Text style={{ fontWeight: '700' }}>{request.status.toUpperCase()}</Text></View>)}</>;
}

export function TripsScreen({ me }) {
  const [trips, setTrips] = useState([]); const load = () => api('/api/trips/mine').then(setTrips).catch((error) => say(error.message)); useEffect(load, []);
  const rate = (tripId, toUser, stars) => api('/api/ratings', { tripId, toUser, stars }).then(load).catch((error) => say(error.message));
  return <><Text style={s.h2}>Trips & Ratings</Text>{trips.length === 0 && <Text style={s.mute}>Completed trips show up here.</Text>}{trips.map((trip) => { const people = [trip.driverId, ...(trip.riders || [])].filter((person) => person && String(person._id) !== String(me?._id)); const rated = trip.rated || []; return <View key={trip._id} style={s.card}><Text style={s.name}>{trip.origin?.name || 'Unknown pickup'} → {trip.dest?.name || 'Unknown destination'}</Text><Text style={s.mute}>{trip.createdAt ? new Date(trip.createdAt).toDateString() : 'Recent trip'} · {trip.distanceKm || 0} km</Text><Text style={{ fontSize: 22, fontWeight: '800', marginVertical: 6 }}>Rs. {trip.perPerson || 0} each</Text>{people.map((person) => <View key={person._id} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text>{person.name || 'Participant'}</Text>{rated.includes(String(person._id)) ? <Text style={s.mute}>Rated ✓</Text> : <Stars v={0} set={(stars) => rate(trip._id, person._id, stars)} />}</View>)}</View>; })}</>;
}

export function ProfileScreen({ me, logout, go, setForm }) {
  const [commutes, setCommutes] = useState([]); const [profile, setProfile] = useState(null); const load = () => { api('/api/commutes/mine').then(setCommutes).catch(() => {}); api(`/api/users/${me._id}`).then(setProfile).catch(() => {}); }; useEffect(load, []);
  return <><Text style={s.h2}>Profile</Text><View style={s.card}><Text style={s.name}>{me.name}</Text><Text style={s.mute}>{me.phone} · {me.email}</Text><Text style={{ marginTop: 6 }}>★ {profile?.avg || 'New'} · {profile?.count || 0} ratings</Text></View><Text style={s.lbl}>My commutes</Text>{commutes.length === 0 && <Text style={s.mute}>Nothing posted yet — use the ＋ tab.</Text>}{commutes.map((commute) => <View key={commute._id} style={s.card}><Text style={{ fontWeight: '700' }}>{commute.origin.name} → {commute.dest.name}</Text><Text style={s.mute}>{commute.startTime}–{commute.endTime} · {commute.role} · {commute.days.map((day) => DAYS[day]).join('')} · {commute.paused ? 'Paused' : 'Active'}</Text><View style={{ flexDirection: 'row', gap: 14, marginTop: 10 }}><Text onPress={() => { setForm({ ...commute, seats: String(commute.seats), price: String(commute.price) }); go('post'); }} style={{ color: C.blue, fontWeight: '700' }}>Edit</Text><Text onPress={() => api(`/api/commutes/${commute._id}`, { paused: !commute.paused }, 'PATCH').then(load)} style={{ fontWeight: '700' }}>{commute.paused ? 'Resume' : 'Pause'}</Text><Text onPress={() => api(`/api/commutes/${commute._id}`, null, 'DELETE').then(load)} style={{ color: C.red, fontWeight: '700' }}>Delete</Text></View></View>)}<Btn dark t="Log out" onPress={logout} /></>;
}
